version: '3.8'

services:
  # Основное приложение
  legal-bot:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: legal-bot-test
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CHROMA_DB_PATH=/app/db/chroma
      - ENVIRONMENT=test
      - LOG_LEVEL=INFO
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data:ro
      - test-db-data:/app/db
      - test-logs:/app/logs
      - test-models:/app/models
    env_file:
      - env.test.local
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "python", "-c", "print('Health check passed')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Redis для кэширования
  redis:
    image: redis:7-alpine
    container_name: legal-bot-redis-test
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-test-data:/data
    networks:
      - test-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Nginx (упрощенная версия)
  nginx:
    image: nginx:alpine
    container_name: legal-bot-nginx-test
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.test.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - legal-bot
    networks:
      - test-network

# Сети
networks:
  test-network:
    driver: bridge

# Постоянные тома
volumes:
  test-db-data:
    driver: local
  test-logs:
    driver: local
  test-models:
    driver: local
  redis-test-data:
    driver: local 