apiVersion: v1
kind: ConfigMap
metadata:
  name: legal-bot-config
  namespace: legal-bot
data:
  ENVIRONMENT: "production"
  REDIS_URL: "redis://redis-service:6379"
  LOG_LEVEL: "INFO"
  MAX_WORKERS: "4"
  TIMEOUT: "30"
  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: legal-bot
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream legal_bot {
            server legal-bot-service:5000;
        }
        
        server {
            listen 80;
            server_name _;
            
            location / {
                proxy_pass http://legal_bot;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            location /health {
                access_log off;
                return 200 "healthy\n";
                add_header Content-Type text/plain;
            }
        }
    } 