apiVersion: v1
kind: Secret
metadata:
  name: legal-bot-secrets
  namespace: legal-bot
type: Opaque
data:
  # Base64 encoded values - replace with actual values
  DATABASE_URL: cG9zdGdyZXNxbDovL3VzZXI6cGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9sZWdhbF9ib3Q=
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2tleV9oZXJl
  OPENAI_API_KEY: eW91cl9vcGVuYWlfa2V5X2hlcmU=
  REDIS_PASSWORD: eW91cl9yZWRpc19wYXNzd29yZF9oZXJl
  
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: legal-bot
type: Opaque
data:
  POSTGRES_DB: bGVnYWxfYm90
  POSTGRES_USER: cG9zdGdyZXM=
  POSTGRES_PASSWORD: cG9zdGdyZXM=
  
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
  namespace: legal-bot
type: Opaque
data:
  GF_SECURITY_ADMIN_PASSWORD: YWRtaW4= 