version: '3.8'

services:
  legal-bot:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/legal-bot:${IMAGE_TAG:-latest}
    container_name: legal-bot-aws
    restart: unless-stopped
    environment:
      - ENVIRONMENT=production
      - REDIS_URL=redis://redis:6379
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CLOUDFRONT_DOMAIN=${CLOUDFRONT_DOMAIN}
      - RDS_ENDPOINT=${RDS_ENDPOINT}
      - ELASTICACHE_ENDPOINT=${ELASTICACHE_ENDPOINT}
    depends_on:
      - redis
    networks:
      - legal-bot-network
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/legal-bot
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecs

  nginx:
    image: nginx:alpine
    container_name: nginx-aws
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.aws.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/security:/etc/nginx/security:ro
    depends_on:
      - legal-bot
    networks:
      - legal-bot-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.2'
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/nginx
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecs

  redis:
    image: redis:7-alpine
    container_name: redis-aws
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data
    networks:
      - legal-bot-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/redis
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecs

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-aws
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus.aws.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - legal-bot-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/prometheus
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecs

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-aws
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL}
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=${SMTP_HOST}
      - GF_SMTP_USER=${SMTP_USER}
      - GF_SMTP_PASSWORD=${SMTP_PASSWORD}
      - GF_SMTP_FROM_ADDRESS=${SMTP_FROM_ADDRESS}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - prometheus
    networks:
      - legal-bot-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.3'
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/grafana
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecs

  backup:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/legal-bot-backup:${IMAGE_TAG:-latest}
    container_name: backup-aws
    restart: unless-stopped
    environment:
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - S3_BACKUP_BUCKET=${S3_BACKUP_BUCKET}
      - RDS_ENDPOINT=${RDS_ENDPOINT}
      - DATABASE_URL=${DATABASE_URL}
      - BACKUP_SCHEDULE=${BACKUP_SCHEDULE:-0 2 * * *}
    volumes:
      - backup-data:/backups
      - ./scripts:/scripts:ro
    networks:
      - legal-bot-network
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: '0.1'
    logging:
      driver: awslogs
      options:
        awslogs-group: /ecs/backup
        awslogs-region: ${AWS_REGION}
        awslogs-stream-prefix: ecs

networks:
  legal-bot-network:
    driver: bridge

volumes:
  redis-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  backup-data:
    driver: local 