global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'legal-bot-prod'
    environment: 'production'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Legal Bot application
  - job_name: 'legal-bot'
    static_configs:
      - targets: 
        - 'legal-bot_1:5000'
        - 'legal-bot_2:5000'
        - 'legal-bot_3:5000'
        - 'legal-bot_4:5000'
        - 'legal-bot_5:5000'
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # PostgreSQL metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 30s

  # Blackbox exporter for endpoint monitoring
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://legal-bot.com/health
        - https://legal-bot.com/api/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # HAProxy metrics
  - job_name: 'haproxy'
    static_configs:
      - targets: ['haproxy:8404']
    metrics_path: '/stats/prometheus'
    scrape_interval: 30s

  # Security monitor metrics
  - job_name: 'security-monitor'
    static_configs:
      - targets: ['security-monitor:8080']
    scrape_interval: 60s

  # Custom application metrics
  - job_name: 'legal-bot-custom'
    static_configs:
      - targets: 
        - 'legal-bot_1:5000'
        - 'legal-bot_2:5000'
        - 'legal-bot_3:5000'
        - 'legal-bot_4:5000'
        - 'legal-bot_5:5000'
    metrics_path: '/custom-metrics'
    scrape_interval: 30s

  # ML model metrics
  - job_name: 'ml-model'
    static_configs:
      - targets: 
        - 'legal-bot_1:5000'
        - 'legal-bot_2:5000'
        - 'legal-bot_3:5000'
        - 'legal-bot_4:5000'
        - 'legal-bot_5:5000'
    metrics_path: '/ml-metrics'
    scrape_interval: 60s

  # Business metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: 
        - 'legal-bot_1:5000'
        - 'legal-bot_2:5000'
        - 'legal-bot_3:5000'
        - 'legal-bot_4:5000'
        - 'legal-bot_5:5000'
    metrics_path: '/business-metrics'
    scrape_interval: 300s  # 5 minutes

# Remote write configuration for long-term storage
remote_write:
  - url: "https://prometheus-remote-write.example.com/api/v1/write"
    basic_auth:
      username: "prometheus"
      password: "secure_password"
    queue_config:
      max_samples_per_send: 1000
      max_shards: 200
      capacity: 2500 